package defiletalents;

import javax.swing.JFrame;

/**
 * Classe permettant de gérer un calendrier.
 * @author giraudeaup
 */
public class V_Calendrier extends javax.swing.JDialog
{

    /**
     * Parent appelant cette vue.
     */
    private JFrame parent;

    /**
     * Constructeur de la vue.
     */
    public V_Calendrier()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        btFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        dateChooserPanel1.addCommitListener(new datechooser.events.CommitListener()
        {
            public void onCommit(datechooser.events.CommitEvent evt)
            {
                dateChooserPanel1OnCommit(evt);
            }
        });

        btFermer.setText("Fermer");
        btFermer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btFermer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode utilisée à la selection d'une date dans le calendrier. Redirige ensuite la date selectionnée à la vue concernée.
     * @param evt 
     */
    private void dateChooserPanel1OnCommit(datechooser.events.CommitEvent evt)//GEN-FIRST:event_dateChooserPanel1OnCommit
    {//GEN-HEADEREND:event_dateChooserPanel1OnCommit
        if (parent.getClass().toString().contains("V_Achat_Edit"))
        {
            ((V_Achat_Edit) parent).setSelectedDate(dateChooserPanel1.getCurrent());
            ((V_Achat_Edit) parent).setVisible(true);
        }
        if (parent.getClass().toString().contains("V_Paiement_Edit"))
        {
            ((V_Paiement_Edit) parent).setSelectedDate(dateChooserPanel1.getCurrent());
            ((V_Paiement_Edit) parent).setVisible(true);
        }

        setVisible(false);
    }//GEN-LAST:event_dateChooserPanel1OnCommit

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Fermer'.
     * @param evt 
     */
    private void btFermerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btFermerActionPerformed
    {//GEN-HEADEREND:event_btFermerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btFermerActionPerformed

    /**
     * Surcharge de la méthode setVisible(boolean b).
     * @param b 
     */
    @Override
    public void setVisible(boolean b)
    {
        setLocationRelativeTo(parent);

        super.setVisible(b);
    }
    
    /**
     * Définit le parent appelant cette vue.
     * @param parent 
     */
    public void setValues(JFrame parent)
    {
        this.parent = parent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFermer;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    // End of variables declaration//GEN-END:variables
}
