package defiletalents;

import javax.swing.JDialog;
import javax.swing.UIManager;

/**
 * Classe permettant d'afficher des messages d'erreurs à l'utilisateur.
 *
 * @author giraudeaup
 */
public class V_ErrMessage extends JDialog {

    /**
     * Constructeur de la vue.
     */
    public V_ErrMessage() {
        initComponents();
        setTitle("Erreur");
        jScrollPane1.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbWarning = new javax.swing.JTextArea();

        setModal(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        setSize(new java.awt.Dimension(450, 150));

        btClose.setText("Fermer");
        btClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCloseActionPerformed(evt);
            }
        });

        lbWarning.setEditable(false);
        lbWarning.setBackground(UIManager.getColor("Label.background"));
        lbWarning.setColumns(20);
        lbWarning.setFont(UIManager.getFont("Label.font"));
        lbWarning.setLineWrap(true);
        lbWarning.setRows(2);
        lbWarning.setTabSize(4);
        lbWarning.setText("TEXT DE TEST");
        lbWarning.setWrapStyleWord(true);
        lbWarning.setBorder(null);
        lbWarning.setFocusable(false);
        lbWarning.setOpaque(false);
        jScrollPane1.setViewportView(lbWarning);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 326, Short.MAX_VALUE)
                        .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btClose)
                .addContainerGap())
        );

        setBounds(0, 0, 460, 180);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Fermer'.
     *
     * @param evt
     */
    private void btCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCloseActionPerformed
    {//GEN-HEADEREND:event_btCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * Surcharge de la méthode setVisible(boolean b)
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        if (b) {
            setLocationRelativeTo(null);
        }
        super.setVisible(b);
    }

    /**
     * Défini un message d'erreur pour cette vue.
     *
     * @param message
     */
    public void setMessage(String message) {
        lbWarning.setText(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lbWarning;
    // End of variables declaration//GEN-END:variables
}
