package defiletalents;

import java.io.File;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class V_InitDb extends javax.swing.JDialog {

    private Controller controller;
    private JFileChooser explorer;

    public V_InitDb(Controller controller) {
        this.controller = controller;
        explorer = new JFileChooser();
        explorer.setFileFilter(new FileNameExtensionFilter("Fichiers SQLite (.sqlite, .sq3)", "sqlite", "sq3"));
        explorer.setAcceptAllFileFilterUsed(false);
        explorer.setLocale(Locale.FRENCH);
        explorer.updateUI();
        initComponents();
        setTitle("Billeterie > Init");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOpen = new javax.swing.JButton();
        btCreate = new javax.swing.JButton();
        btImport = new javax.swing.JButton();
        btQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        btOpen.setText("Ouvrir...");
        btOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenActionPerformed(evt);
            }
        });

        btCreate.setText("Creer...");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });

        btImport.setText("Creer à partir de...");
        btImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImportActionPerformed(evt);
            }
        });

        btQuit.setText("Quitter");
        btQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btImport, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btImport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btQuit)
                .addGap(33, 33, 33))
        );

        setBounds(0, 0, 219, 286);
    }// </editor-fold>//GEN-END:initComponents

    private void btOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenActionPerformed
        explorer.showDialog(this, "Ouvrir");
        if (explorer.getSelectedFile() != null) {
            controller.openDb(explorer.getSelectedFile());
            setVisible(false);
        }
    }//GEN-LAST:event_btOpenActionPerformed

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        explorer.showSaveDialog(this);
        if (explorer.getSelectedFile() != null) {
            if (!explorer.getSelectedFile().exists()) {
                String filename = explorer.getSelectedFile().getAbsolutePath();
                if (!(filename.endsWith(".sqlite") || filename.endsWith(".sq3"))) {
                    filename += ".sqlite";
                    controller.newDb(filename);
                    setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_btCreateActionPerformed

    private void btImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImportActionPerformed
        File oldDb;
        File newDb;

        explorer.setApproveButtonToolTipText("Base de données SOURCE");
        explorer.showDialog(this, "Ouvrir");
        if (explorer.getSelectedFile() != null) {
            oldDb = explorer.getSelectedFile();
            explorer.setApproveButtonToolTipText("Base de données CIBLE");
            explorer.showDialog(this, "Creer");
            if (explorer.getSelectedFile() != null && explorer.getSelectedFile() != oldDb) {
                newDb = explorer.getSelectedFile();
                controller.importDb(oldDb, newDb);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_btImportActionPerformed

    private void btQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btQuitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btImport;
    private javax.swing.JButton btOpen;
    private javax.swing.JButton btQuit;
    // End of variables declaration//GEN-END:variables
}
