package defiletalents;

import javax.swing.table.DefaultTableModel;

/**
 * Classe permettant de gérer la vue relative à la talbe tal_ligne.
 *
 * @author giraudeaup
 */
public class V_Ligne_All extends javax.swing.JFrame {

    /**
     * Controleur de l'appli.
     */
    private Controller controller;
    /**
     * Identifiant de la vue.
     */
    private int id_achat = 0;

    /**
     * Constructeur de la vue.
     *
     * @param controller
     */
    public V_Ligne_All(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLignes = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        btClose.setText("Fermer");
        btClose.setMaximumSize(new java.awt.Dimension(160, 160));
        btClose.setMinimumSize(new java.awt.Dimension(160, 160));
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        tableLignes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Place", "Catégorie de prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLignes.setMaximumSize(new java.awt.Dimension(480, 18));
        tableLignes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableLignes);
        if (tableLignes.getColumnModel().getColumnCount() > 0) {
            tableLignes.getColumnModel().getColumn(0).setMinWidth(0);
            tableLignes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableLignes.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btAdd.setText("Ajouter...");
        btAdd.setMaximumSize(new java.awt.Dimension(160, 160));
        btAdd.setMinimumSize(new java.awt.Dimension(160, 160));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setText("Modifier...");
        btEdit.setMaximumSize(new java.awt.Dimension(160, 160));
        btEdit.setMinimumSize(new java.awt.Dimension(160, 160));
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDel.setText("Supprimer...");
        btDel.setMaximumSize(new java.awt.Dimension(160, 160));
        btDel.setMinimumSize(new java.awt.Dimension(160, 160));
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setBounds(0, 0, 650, 510);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Fermer'.
     *
     * @param evt
     */
    private void btCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCloseActionPerformed
    {//GEN-HEADEREND:event_btCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Ajouter'.
     *
     * @param evt
     */
    private void btAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAddActionPerformed
    {//GEN-HEADEREND:event_btAddActionPerformed
        controller.getLigneEditFrame(getId_Achat(), V_Main.MODE_AJOUT).setVisible(true);
    }//GEN-LAST:event_btAddActionPerformed

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Modifier'.
     *
     * @param evt
     */
    private void btEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btEditActionPerformed
    {//GEN-HEADEREND:event_btEditActionPerformed
        if (tableLignes.getSelectedRow() != -1) {
            controller.getLigneEditFrame(getId_Achat(), (int) tableLignes.getValueAt(tableLignes.getSelectedRow(), 0), V_Main.MODE_EDITION).setVisible(true);
        }
    }//GEN-LAST:event_btEditActionPerformed

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Supprimer'.
     *
     * @param evt
     */
    private void btDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btDelActionPerformed
    {//GEN-HEADEREND:event_btDelActionPerformed
        if (tableLignes.getSelectedRow() != -1) {
            String id = id_achat + ";" + tableLignes.getValueAt(tableLignes.getSelectedRow(), 0);
            controller.getDeleteConfirmFrame("ligne", id).setVisible(true);
        }
    }//GEN-LAST:event_btDelActionPerformed

    /**
     * Surcharge de la méthode setVisible(boolean b).
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        if (b) {
            setTitle("Places pour la vente " + getId_Achat());
            setLocationRelativeTo(controller.getMainFrame());
            setTable();
        }

        super.setVisible(b);
    }

    /**
     * Met à jour le tableau utilisé par la vue.
     */
    private void setTable() {
        DefaultTableModel model = (DefaultTableModel) tableLignes.getModel();
        int size = controller.getLignes().size();
        int i = 0;
        String place = "null";
        String categorie = "null";
        model.setRowCount(size);

        for (M_Ligne l : controller.getLignes()) {
            if (l.getIdAchat() == id_achat) {
                model.setValueAt(l.getId(), i, 0);
                place = ((controller.getPlace(l.getIdPlace()) != null) ? controller.getPlace(l.getIdPlace()).getCode() : "null");
                model.setValueAt(place, i, 1);
                categorie = ((controller.getCategoriePrix(l.getIdCategorie()) != null) ? controller.getCategoriePrix(l.getIdCategorie()).getLibelle() : "null");
                model.setValueAt(categorie, i, 2);
                i++;
            }
        }
        model.setRowCount(i);
        tableLignes.setModel(model);
    }

    /**
     * Valorise l'identifiant de la vue.
     *
     * @param id_achat
     */
    public void setValues(int id_achat) {
        this.id_achat = id_achat;
    }

    /**
     * Retourne l'identifiant de la vue
     *
     * @return
     */
    public int getId_Achat() {
        return this.id_achat;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLignes;
    // End of variables declaration//GEN-END:variables
}
