package defiletalents;

import javax.swing.table.DefaultTableModel;

/**
 * Classe permettant de gérer la vue relative à la table tal_mode_paiement.
 *
 * @author giraudeaup
 */
public class V_ModePaiement_All extends javax.swing.JFrame {

    /**
     * Controleur de l'appli.
     */
    private Controller controller;

    /**
     * Constructeur de la vue.
     *
     * @param controller
     */
    public V_ModePaiement_All(Controller controller) {
        this.controller = controller;
        initComponents();
        setTitle("Paramètres > Modes de paiement");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableModePaiement = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        tableModePaiement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null}
            },
            new String []
            {
                "Id", "Code", "Libelle"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableModePaiement);
        if (tableModePaiement.getColumnModel().getColumnCount() > 0)
        {
            tableModePaiement.getColumnModel().getColumn(0).setMinWidth(0);
            tableModePaiement.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableModePaiement.getColumnModel().getColumn(0).setMaxWidth(0);
            tableModePaiement.getColumnModel().getColumn(1).setMinWidth(90);
            tableModePaiement.getColumnModel().getColumn(1).setPreferredWidth(90);
            tableModePaiement.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        btAdd.setText("Ajouter...");
        btAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setText("Modifier...");
        btEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btEditActionPerformed(evt);
            }
        });

        btDel.setText("Supprimer...");
        btDel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btDelActionPerformed(evt);
            }
        });

        btClose.setText("Fermer");
        btClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBounds(0, 0, 650, 510);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode utilisée lorque l'on appuie sur le bouton 'Fermer'.
     *
     * @param evt
     */
    private void btCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCloseActionPerformed
    {//GEN-HEADEREND:event_btCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * Méthode utilisée lorque l'on appuie sur le bouton 'Ajouter'.
     *
     * @param evt
     */
    private void btAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAddActionPerformed
    {//GEN-HEADEREND:event_btAddActionPerformed
        controller.getModePaiementEditFrame(V_Main.MODE_AJOUT).setVisible(true);
    }//GEN-LAST:event_btAddActionPerformed

    /**
     * Méthode utilisée lorque l'on appuie sur le bouton 'Modifier'.
     *
     * @param evt
     */
    private void btEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btEditActionPerformed
    {//GEN-HEADEREND:event_btEditActionPerformed
        if (tableModePaiement.getSelectedRow() != -1) {
            controller.getModePaiementEditFrame((int) tableModePaiement.getModel().getValueAt(tableModePaiement.getSelectedRow(), 0), V_Main.MODE_EDITION).setVisible(true);
        }
    }//GEN-LAST:event_btEditActionPerformed

    /**
     * Méthode utilisée lorque l'on appuie sur le bouton 'Supprimer'.
     *
     * @param evt
     */
    private void btDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btDelActionPerformed
    {//GEN-HEADEREND:event_btDelActionPerformed
        if (tableModePaiement.getSelectedRow() != -1) {
            controller.getDeleteConfirmFrame("Modepaiement", String.valueOf((int) tableModePaiement.getModel().getValueAt(tableModePaiement.getSelectedRow(), 0))).setVisible(true);
        }
    }//GEN-LAST:event_btDelActionPerformed

    /**
     * Surcharge de la méthode setVisible(boolean b).
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        if (b) {
            setLocationRelativeTo(controller.getMainFrame());
            setTable();
        }
        super.setVisible(b);
    }

    /**
     * Met à jour le tableau utilisé par la vue.
     */
    private void setTable() {
        DefaultTableModel model = (DefaultTableModel) tableModePaiement.getModel();
        int size = controller.getModesPaiement().size();

        int i = 0;

        model.setRowCount(size);

        for (M_Mode_Paiement m : controller.getModesPaiement()) {
            model.setValueAt(m.getId(), i, 0);
            model.setValueAt(m.getCode(), i, 1);
            model.setValueAt(m.getLibelle(), i, 2);
            i++;
        }
        tableModePaiement.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableModePaiement;
    // End of variables declaration//GEN-END:variables
}
