package defiletalents;

import java.io.File;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import methodesVerif.Verify;

/**
 * Classe permettant de gérer la vue relative à un enregistrement de la table
 * tal_plan.
 *
 * @author giraudeaup
 */
public class V_Plan_Edit extends javax.swing.JDialog {

    /**
     * Controleur de l'appli.
     */
    private Controller controller;
    /**
     * Identifiant de l'enregistrement.
     */
    private int id = 0;
    /**
     * Mode de la vue.
     */
    private int mode = 0;

    /**
     * Exporateur de fichiers utilisé pour récupérer un lien vers une image.
     */
    private JFileChooser explorer;

    /**
     * Constructeur de la vue.
     *
     * @param controller
     */
    public V_Plan_Edit(Controller controller) {
        this.controller = controller;
        initComponents();
        explorer = new JFileChooser();
        explorer.setFileFilter(new FileNameExtensionFilter("Images (.jpg, .jpeg, .png)", "jpg", "jpeg", "png"));
        explorer.setAcceptAllFileFilterUsed(false);
        explorer.setLocale(Locale.FRENCH);
        explorer.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCode = new javax.swing.JLabel();
        edLibelle = new javax.swing.JTextField();
        lbLibelle = new javax.swing.JLabel();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();
        edImage = new javax.swing.JTextField();
        btImage = new javax.swing.JButton();
        lbWarning = new javax.swing.JLabel();
        lbWidth = new javax.swing.JLabel();
        lbHeight = new javax.swing.JLabel();
        edWidth = new javax.swing.JTextField();
        edHeight = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        lbCode.setText("Libelle:");

        edLibelle.setNextFocusableComponent(btImage);

        lbLibelle.setText("Image:");

        btValider.setText("Valider");
        btValider.setNextFocusableComponent(btAnnuler);
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");
        btAnnuler.setNextFocusableComponent(edLibelle);
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        edImage.setEditable(false);

        btImage.setText("...");
        btImage.setNextFocusableComponent(btValider);
        btImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImageActionPerformed(evt);
            }
        });

        lbWidth.setText("Largeur de la place:");

        lbHeight.setText("Hauteur de la place:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btValider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edLibelle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edImage, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, 0)
                        .addComponent(btImage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(edWidth, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbWidth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edHeight))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(edImage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addComponent(btImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWidth)
                    .addComponent(lbHeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnnuler)
                    .addComponent(btValider))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton de selection d'une
     * image via l'explorer.
     *
     * @param evt
     */
    private void btImageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btImageActionPerformed
    {//GEN-HEADEREND:event_btImageActionPerformed

        explorer.showOpenDialog(this);
        if (explorer.getSelectedFile() != null) {
            if (explorer.getSelectedFile().exists()) {
                edImage.setText(explorer.getSelectedFile().getAbsolutePath());
            }
            else {
                lbWarning.setText("Le fichier image n'est pas valide.");
                edImage.setText("");
            }
        }

    }//GEN-LAST:event_btImageActionPerformed

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Valider'.
     *
     * @param evt
     */
    private void btValiderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btValiderActionPerformed
    {//GEN-HEADEREND:event_btValiderActionPerformed
        boolean errors = false;
        if (edLibelle.getText().equals("")) {
            errors = true;
        }
        int width = Verify.toInt(edWidth.getText());
        int height = Verify.toInt(edHeight.getText());

        if (!errors) {
            controller.updatePlan(id, edLibelle.getText(), edImage.getText(), width, height);
            controller.getPlanAllFrame().setVisible(true);
            setVisible(false);
        }
        else {
            lbWarning.setText("Erreur: Le champs libellé est requis.");
        }

    }//GEN-LAST:event_btValiderActionPerformed

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Annuler'.
     *
     * @param evt
     */
    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAnnulerActionPerformed
    {//GEN-HEADEREND:event_btAnnulerActionPerformed
        edLibelle.setEditable(true);
        btImage.setEnabled(true);
        edWidth.setEnabled(true);
        edHeight.setEnabled(true);
        btValider.setVisible(true);
        btAnnuler.setText("Annuler");
        setVisible(false);
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * Surcharge de la méthode setVisible(boolean b).
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        if (b) {
            setLocationRelativeTo(controller.getPlanAllFrame());
            lbWarning.setText("");
        }

        super.setVisible(b);
    }

    /**
     * Met à jour les valeurs utilisées par la vue.
     *
     * @param id
     * @param libelle
     * @param image
     * @param width
     * @param height
     * @param mode
     */
    public void setValues(int id, String libelle, String image, int width, int height, int mode) {
        this.id = id;
        this.mode = mode;

        switch (mode) {
            case V_Main.MODE_AJOUT:
                setTitle("Ajout d'un nouveau plan");
                edLibelle.setText("");
                edImage.setText("");
                edWidth.setText("");
                edHeight.setText("");
                break;
            case V_Main.MODE_EDITION:
                setTitle("Edition du plan " + id);
                edLibelle.setText(libelle);
                edImage.setText(image);
                edWidth.setText(Integer.toString(width));
                edHeight.setText(Integer.toString(height));
                break;
            default:
                setTitle("Consultation du plan " + id);
                edLibelle.setText(libelle);
                edImage.setText(image);
                edWidth.setText(Integer.toString(width));
                edHeight.setText(Integer.toString(height));
                edLibelle.setEditable(false);
                btImage.setEnabled(false);
                edWidth.setEnabled(false);
                edHeight.setEnabled(false);
                btValider.setVisible(false);
                btAnnuler.setText("Fermer");
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btImage;
    private javax.swing.JButton btValider;
    private javax.swing.JTextField edHeight;
    private javax.swing.JTextField edImage;
    private javax.swing.JTextField edLibelle;
    private javax.swing.JTextField edWidth;
    private javax.swing.JLabel lbCode;
    private javax.swing.JLabel lbHeight;
    private javax.swing.JLabel lbLibelle;
    private javax.swing.JLabel lbWarning;
    private javax.swing.JLabel lbWidth;
    // End of variables declaration//GEN-END:variables
}
