package defiletalents;

/**
 * Classe permettant d'afficher les images du plan.
 *
 * @author giraudeaup
 */
public class V_Plans extends javax.swing.JFrame {

    /**
     * Controleur de l'appli.
     */
    private Controller controller;

    /**
     * Constructeur de la vue.
     *
     * @param controller
     */
    public V_Plans(Controller controller) {
        this.controller = controller;
        initComponents();
        setLocationRelativeTo(controller.getMainFrame());
        setTitle("Plans");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNext = new javax.swing.JButton();
        btPrevious = new javax.swing.JButton();
        lbCurrent = new javax.swing.JLabel();
        planPanel = new PlanPanel(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(894, 558));

        btNext.setText(">");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        btPrevious.setText("<");
        btPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreviousActionPerformed(evt);
            }
        });

        lbCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCurrent.setText("Plan");
        lbCurrent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        planPanel.setMaximumSize(new java.awt.Dimension(1169, 826));
        planPanel.setMinimumSize(new java.awt.Dimension(1169, 826));
        planPanel.setPreferredSize(new java.awt.Dimension(1169, 826));

        javax.swing.GroupLayout planPanelLayout = new javax.swing.GroupLayout(planPanel);
        planPanel.setLayout(planPanelLayout);
        planPanelLayout.setHorizontalGroup(
            planPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        planPanelLayout.setVerticalGroup(
            planPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(lbCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(planPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btPrevious, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCurrent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(planPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 1203, 919);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Affiche l'image précedante.
     *
     * @param evt
     */
    private void btPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreviousActionPerformed
        planPanel.decrementChoice();
        lbCurrent.setText("Plan " + (planPanel.getCurrentChoice() + 1) + " sur " + planPanel.nbImages());
        planPanel.render();
    }//GEN-LAST:event_btPreviousActionPerformed

    /**
     * Affiche l'image suivante.
     *
     * @param evt
     */
    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        planPanel.incrementChoice();
        lbCurrent.setText("Plan " + (planPanel.getCurrentChoice() + 1) + " sur " + planPanel.nbImages());
        planPanel.render();
    }//GEN-LAST:event_btNextActionPerformed

    /**
     * Surcharge de la méthode héritée setVisible(boolean b).
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b) {
            planPanel.render();
            lbCurrent.setText("Plan " + (planPanel.getCurrentChoice() + 1) + " sur " + planPanel.nbImages());
        }
    }

    public void setImages(String... paths) {
        planPanel.loadImages(paths);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNext;
    private javax.swing.JButton btPrevious;
    private javax.swing.JLabel lbCurrent;
    private PlanPanel planPanel;
    // End of variables declaration//GEN-END:variables

}
