package defiletalents;

/**
 * Classe permettant de gérer la vue de recherche par mot clés.
 *
 * @author giraudeaup
 */
public class V_Recherche extends javax.swing.JFrame {

    /**
     * Controleur de l'appli.
     */
    private Controller controller;

    /**
     * Constructeur de la vue.
     *
     * @param controller
     */
    public V_Recherche(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        edRechercher = new javax.swing.JTextField();
        btRechercher = new javax.swing.JButton();
        rdPlace = new javax.swing.JRadioButton();
        rdNom = new javax.swing.JRadioButton();
        lbWarning = new javax.swing.JLabel();

        setResizable(false);

        btRechercher.setText("Rechercher");
        btRechercher.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRechercherActionPerformed(evt);
            }
        });

        rdPlace.setText("Par code de place");
        rdPlace.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdPlaceActionPerformed(evt);
            }
        });

        rdNom.setSelected(true);
        rdNom.setText("Par nom de client");
        rdNom.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdNomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdNom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdPlace)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btRechercher))
                            .addComponent(edRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(edRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRechercher)
                    .addComponent(rdPlace)
                    .addComponent(rdNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Selectioonne le bouton radio 'par nom' et de-selectionne le bouton radio
     * 'par place'.
     *
     * @param evt
     */
    private void rdNomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdNomActionPerformed
    {//GEN-HEADEREND:event_rdNomActionPerformed
        rdNom.setSelected(true);
        rdPlace.setSelected(false);
    }//GEN-LAST:event_rdNomActionPerformed

    /**
     * Selectioonne le bouton radio 'par place' et de-selectionne le bouton
     * radio 'par nom'.
     *
     * @param evt
     */
    private void rdPlaceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdPlaceActionPerformed
    {//GEN-HEADEREND:event_rdPlaceActionPerformed
        rdNom.setSelected(false);
        rdPlace.setSelected(true);
    }//GEN-LAST:event_rdPlaceActionPerformed

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Rechercher'
     *
     * @param evt
     */
    private void btRechercherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRechercherActionPerformed
    {//GEN-HEADEREND:event_btRechercherActionPerformed
        if (!edRechercher.getText().equals("")) {
            controller.rechercher(edRechercher.getText(), rdNom.isSelected());
        }
        else {
            lbWarning.setText("Le champs de recherche est vide.");
        }
    }//GEN-LAST:event_btRechercherActionPerformed

    /**
     * Surcharge de la méthode setVisible(boolean b).
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        if (b) {
            setLocationRelativeTo(controller.getMainFrame());
            setTitle("Recherche");
            edRechercher.setText("");
            rdNom.setSelected(true);
            rdPlace.setSelected(false);
        }

        super.setVisible(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRechercher;
    private javax.swing.JTextField edRechercher;
    private javax.swing.JLabel lbWarning;
    private javax.swing.JRadioButton rdNom;
    private javax.swing.JRadioButton rdPlace;
    // End of variables declaration//GEN-END:variables
}
