package defiletalents;

import javax.swing.DefaultComboBoxModel;

/**
 * Classe permettant de gérer la vue relative à un enregistrement de la table
 * tal_zone.
 *
 * @author giraudeaup
 */
public class V_Zone_Edit extends javax.swing.JDialog {

    /**
     * Controleur de l'appli.
     */
    private Controller controller;
    /**
     * Identifiant de l'enregistrement.
     */
    private int id = 0;
    /**
     * Mode de la vue.
     */
    private int mode = 0;
    /**
     * Tableau d'entiers représentant les identifiants eds classes de prix.
     */
    private int[] idClasses;

    /**
     * Constructeur de la vue.
     *
     * @param controller
     */
    public V_Zone_Edit(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLibelle = new javax.swing.JLabel();
        edLibelle = new javax.swing.JTextField();
        lbClassePrix = new javax.swing.JLabel();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();
        cbClassePrix = new javax.swing.JComboBox<>();
        lbWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        lbLibelle.setText("Libelle:");

        edLibelle.setNextFocusableComponent(cbClassePrix);

        lbClassePrix.setText("Classe de prix:");

        btValider.setText("Valider");
        btValider.setNextFocusableComponent(btAnnuler);
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");
        btAnnuler.setNextFocusableComponent(edLibelle);
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        cbClassePrix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbClassePrix.setNextFocusableComponent(btValider);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbClassePrix, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbClassePrix, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btValider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbClassePrix, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbClassePrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnnuler)
                    .addComponent(btValider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Annuler'.
     *
     * @param evt
     */
    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAnnulerActionPerformed
    {//GEN-HEADEREND:event_btAnnulerActionPerformed
        edLibelle.setEditable(true);
        cbClassePrix.setEnabled(true);
        btValider.setVisible(true);
        btAnnuler.setText("Annuler");
        setVisible(false);
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * Méthode utilisée lorsque l'on appuie sur le bouton 'Valider'.
     *
     * @param evt
     */
    private void btValiderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btValiderActionPerformed
    {//GEN-HEADEREND:event_btValiderActionPerformed
        String libelle = edLibelle.getText();

        if (!libelle.equals("")) {
            controller.updateZone(id, libelle, idClasses[cbClassePrix.getSelectedIndex()]);
            controller.getZoneAllFrame().setVisible(true);
            setVisible(false);
        }
        else {
            lbWarning.setText("Le champs libellé est requis.");
        }
    }//GEN-LAST:event_btValiderActionPerformed

    /**
     * Surcharge de la méthode setVisible(boolean b).
     *
     * @param b
     */
    @Override
    public void setVisible(boolean b) {
        if (b) {
            setLocationRelativeTo(controller.getZoneAllFrame());
            lbWarning.setText("");
        }

        super.setVisible(b);
    }

    /**
     * Rempli le comboBox relatif aux classes de prix.
     */
    private void setComboClasse() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        idClasses = new int[controller.getClassesPrix().size()];
        int i = 0;

        for (M_Classe_Prix c : controller.getClassesPrix()) {
            model.addElement(c.getLibelle());
            idClasses[i] = c.getId();
            i++;
        }

        cbClassePrix.setModel(model);
    }

    /**
     * Met à jour les valeurs utilisées par la vue.
     *
     * @param id
     * @param libelle
     * @param id_classe
     * @param mode
     */
    public void setValues(int id, String libelle, int id_classe, int mode) {
        this.mode = mode;
        this.id = id;
        setComboClasse();
        int i = 0;

        switch (mode) {
            case V_Main.MODE_AJOUT:
                setTitle("Ajout d'une nouvelle zone");
                edLibelle.setText("");
                cbClassePrix.setSelectedIndex(0);
                break;
            case V_Main.MODE_EDITION:
                setTitle("Edition de la zone " + id);
                edLibelle.setText(libelle);
                i = 0;
                for (i = 0; i < idClasses.length; i++) {
                    if (idClasses[i] == id_classe) {
                        cbClassePrix.setSelectedIndex(i);
                        break;
                    }
                }
                break;
            default:
                setTitle("Consultation de la zone " + id);
                edLibelle.setText(libelle);
                i = 0;
                for (i = 0; i < idClasses.length; i++) {
                    if (idClasses[i] == id_classe) {
                        cbClassePrix.setSelectedIndex(i);
                        break;
                    }
                }
                edLibelle.setEditable(false);
                cbClassePrix.setEnabled(false);
                btValider.setVisible(false);
                btAnnuler.setText("Fermer");
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btValider;
    private javax.swing.JComboBox<String> cbClassePrix;
    private javax.swing.JTextField edLibelle;
    private javax.swing.JLabel lbClassePrix;
    private javax.swing.JLabel lbLibelle;
    private javax.swing.JLabel lbWarning;
    // End of variables declaration//GEN-END:variables
}
